import { describe,it,expect,vi } from 'vitest';
import { createWalletWindow } from './wallet-window';
const url='chrome-extension://test/popup.html';
function setup(){const deps={runtime:{getURL:vi.fn(()=>url),getContexts:vi.fn(async()=>[])},action:{openPopup:vi.fn(async()=>{})},windows:{create:vi.fn(async()=>({id:5,tabs:[{id:7}]})),get:vi.fn(async()=>({id:5,tabs:[{id:7,url}]})),update:vi.fn(async()=>({}))},tabs:{get:vi.fn(async()=>({url,windowId:5})),update:vi.fn(async()=>({}))}};return {deps,opener:createWalletWindow(deps as unknown as Parameters<typeof createWalletWindow>[0])};}
describe('wallet approval window',()=>{
 it('uses the toolbar popup when the browser allows it',async()=>{const {opener,deps}=setup();expect(await opener.open()).toBe(true);expect(deps.action.openPopup).toHaveBeenCalledOnce();expect(deps.windows.create).not.toHaveBeenCalled();});
 it('opens a packaged wallet window when toolbar opening is rejected',async()=>{const {opener,deps}=setup();deps.action.openPopup.mockRejectedValue(new Error('No user gesture'));expect(await opener.open()).toBe(true);expect(deps.windows.create).toHaveBeenCalledWith({url,type:'popup',width:420,height:720,focused:true});});
 it('deduplicates simultaneous requests and focuses the existing fallback',async()=>{const {opener,deps}=setup();deps.action.openPopup.mockRejectedValue(new Error('unavailable'));await Promise.all([opener.open(),opener.open()]);expect(deps.windows.create).toHaveBeenCalledOnce();await opener.open();expect(deps.windows.update).toHaveBeenCalledWith(5,{focused:true});expect(deps.windows.create).toHaveBeenCalledOnce();});
 it('does not focus an unrelated tab after the fallback was navigated away',async()=>{const {opener,deps}=setup();deps.action.openPopup.mockRejectedValue(new Error('unavailable'));await opener.open();deps.windows.get.mockResolvedValue({id:5,tabs:[{id:7,url:'https://example.com'}]});await opener.open();expect(deps.windows.create).toHaveBeenCalledTimes(2);});
 it('reports failure if both browser mechanisms fail',async()=>{const {opener,deps}=setup();deps.action.openPopup.mockRejectedValue(new Error('unavailable'));deps.windows.create.mockRejectedValue(new Error('blocked'));expect(await opener.open()).toBe(false);});
});
