"""Derive rounded extension/store icons from the existing PLabs artwork.

Requires Pillow. No image-generation service or wallet/browser execution.
"""
from pathlib import Path
from io import BytesIO
import base64
import json
from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src/assets/brand/plabs-original.png'
ICONS = ROOT / 'public/icons'
STORE = ROOT / 'releases/store-assets'
PREVIEW = ROOT / 'artifacts/branding'
for directory in (ICONS, STORE, PREVIEW):
    directory.mkdir(parents=True, exist_ok=True)
source = Image.open(SOURCE).convert('RGB')


def logo_mark(micro=False):
    # The original mark is gold on a black plate. Remove only the black plate.
    rgb = source.filter(ImageFilter.MaxFilter(3)) if micro else source.copy()
    alpha = rgb.convert('L').point(lambda value: 255 if value > 4 else 0)
    rgba = rgb.convert('RGBA')
    rgba.putalpha(alpha)
    return rgba.crop(alpha.getbbox())


def rounded_icon(size, store=False):
    scale = 8 if size <= 48 else 4
    n = size * scale
    inset = size / 8 if store else max(1, size / 16)
    left = round(inset * scale)
    right = n - left
    width = right - left
    radius = round(width * 0.255)
    canvas = Image.new('RGBA', (n, n), (0, 0, 0, 0))
    plate = Image.new('RGBA', (n, n), (0, 0, 0, 0))
    draw = ImageDraw.Draw(plate)
    for y in range(left, right):
        ratio = (y - left) / max(1, width - 1)
        color = tuple(round(a + (b - a) * ratio) for a, b in zip((31, 36, 28), (13, 19, 16)))
        draw.line((left, y, right - 1, y), fill=(*color, 255))
    mask = Image.new('L', (n, n), 0)
    ImageDraw.Draw(mask).rounded_rectangle((left, left, right - 1, right - 1), radius=radius, fill=255)
    plate.putalpha(mask)
    canvas.alpha_composite(plate)
    ImageDraw.Draw(canvas).rounded_rectangle((left, left, right - 1, right - 1), radius=radius,
        outline=(70, 76, 52, 255), width=max(1, round(scale * (0.6 if size <= 48 else size / 180))))
    mark = logo_mark(micro=size <= 32)
    mark_width = round(width * (0.91 if size <= 32 else 0.87))
    mark_height = round(mark.height * mark_width / mark.width)
    mark = mark.resize((mark_width, mark_height), Image.Resampling.LANCZOS)
    canvas.alpha_composite(mark, ((n - mark_width) // 2, (n - mark_height) // 2))
    canvas = canvas.resize((size, size), Image.Resampling.LANCZOS)
    # Keep the official store padding exactly transparent after resampling.
    if store:
        d = ImageDraw.Draw(canvas)
        pad = size // 8
        d.rectangle((0, 0, size - 1, pad - 1), fill=(0, 0, 0, 0))
        d.rectangle((0, size - pad, size - 1, size - 1), fill=(0, 0, 0, 0))
        d.rectangle((0, 0, pad - 1, size - 1), fill=(0, 0, 0, 0))
        d.rectangle((size - pad, 0, size - 1, size - 1), fill=(0, 0, 0, 0))
    return canvas


for size in (16, 24, 32, 48, 64, 128, 256, 512):
    rounded_icon(size, store=size == 128).save(ICONS / f'plabs-{size}.png', optimize=True)
rounded_icon(256).save(ROOT / 'src/assets/plabs-icon.png', optimize=True)
provider_data = 'data:image/png;base64,' + base64.b64encode((ROOT / 'src/assets/plabs-icon.png').read_bytes()).decode('ascii')
(ROOT / 'src/assets/plabs-icon-data.ts').write_text('// Generated by scripts/generate-icons.py; EIP-6963 requires a data URI.\nexport default ' + json.dumps(provider_data) + ';\n')
rounded_icon(128, store=True).save(STORE / 'icon-128.png', optimize=True)
rounded_icon(512, store=True).save(STORE / 'icon-512.png', optimize=True)

# A matching SVG wrapper for website use only; manifests reference PNGs.
mark = logo_mark()
buffer = BytesIO()
mark.save(buffer, format='PNG', optimize=True)
encoded = base64.b64encode(buffer.getvalue()).decode('ascii')
height = 195 * mark.height / mark.width
(ICONS / 'plabs.svg').write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="none">
  <defs><linearGradient id="plate" x1="128" y1="16" x2="128" y2="240" gradientUnits="userSpaceOnUse"><stop stop-color="#1f241c"/><stop offset="1" stop-color="#0d1310"/></linearGradient></defs>
  <rect x="16" y="16" width="224" height="224" rx="57" fill="url(#plate)" stroke="#464c34" stroke-width="1.4"/>
  <image x="30.5" y="{(256-height)/2:.3f}" width="195" height="{height:.3f}" href="data:image/png;base64,{encoded}"/>
</svg>\n''')

font_file = ROOT / 'public/fonts/font-0.ttf'
font = lambda size: ImageFont.truetype(str(font_file), size)
preview = Image.new('RGB', (880, 390), '#eef0ec')
pd = ImageDraw.Draw(preview)
pd.rectangle((440, 0, 879, 389), fill='#101714')
for x, color, label in ((0, '#26382d', 'LIGHT'), (440, '#bacdbd', 'DARK')):
    pd.text((x + 30, 22), label + ' / ROUNDED PLABS ICON', font=font(13), fill=color)
    preview.paste(rounded_icon(184), (x + 128, 55), rounded_icon(184))
    for pos, size in enumerate((16, 24, 32, 48)):
        icon = rounded_icon(size)
        center_x = x + 64 + pos * 99
        preview.paste(icon, (center_x - size // 2, 288 - size // 2), icon)
        pd.text((center_x - 10, 329), str(size), font=font(12), fill=color)
preview.save(PREVIEW / 'icons-preview.png', optimize=True)

# Required small store promotional image: branding, not a simulated screenshot.
promo = Image.new('RGB', (440, 280), '#0e1711')
d = ImageDraw.Draw(promo)
for y in range(280):
    d.line((0, y, 439, y), fill=(14 + y // 60, 23 + y // 70, 17 + y // 80))
d.arc((170, -156, 552, 228), 0, 360, fill='#263d2b', width=1)
d.arc((233, -92, 487, 161), 0, 360, fill='#283f2b', width=1)
icon = rounded_icon(120)
promo.paste(icon, (30, 53), icon)
d.text((174, 79), 'PLabs', font=font(32), fill='#efcf7c')
d.text((176, 125), 'Privacy Wallet', font=font(18), fill='#d6e3d5')
d.line((44, 211, 396, 211), fill='#324932', width=1)
d.text((44, 232), 'EVM  /  SELF-CUSTODY  /  PRIVACY', font=font(11), fill='#9ab69d')
promo.save(STORE / 'promo-440x280.png', optimize=True)
print('Rounded PNG icons, store assets and light/dark preview generated.')
