import { describe,it,expect,vi } from 'vitest';
import { createPrivacyAccess, readPagination, readScopes, type ReadContext, type ReadGrant } from './privacy-access';
function fixture(){let context:ReadContext={origin:'https://app.plabs.online',account:'account-a',chainId:'0x8f',privacyAddress:'perc1-a',expiresAt:Date.now()+60000,permissionEpoch:1,revision:1};let grant:ReadGrant|undefined;const approve=vi.fn(async()=>true);const api=createPrivacyAccess({context:async origin=>({...context,origin}),load:async()=>grant,save:async(_origin,value)=>{grant=value;},approve});return {api,approve,change:(updates:Partial<ReadContext>)=>{context={...context,...updates};},readGrant:()=>grant};}
describe('scoped privacy disclosure',()=>{
 it('does not disclose an address or data without explicit approval',async()=>{const f=fixture();expect((await f.api.session('https://app.plabs.online')).address).toBeUndefined();await expect(f.api.read('https://app.plabs.online','balances',async()=> 'secret')).rejects.toMatchObject({code:4100});expect(f.approve).not.toHaveBeenCalled();});
 it('grants only requested scopes plus address and reuses an existing session',async()=>{const f=fixture();const result=await f.api.request('https://app.plabs.online',{scopes:['balances']});expect(result.scopes).toEqual(['address','balances']);await f.api.request('https://app.plabs.online',{scopes:['balances']});expect(f.approve).toHaveBeenCalledTimes(1);await expect(f.api.read('https://app.plabs.online','history',async()=>[])).rejects.toMatchObject({code:4100});expect(await f.api.read('https://app.plabs.online','balances',async()=>({assets:[]}))).toEqual({assets:[]});});
 it.each([{account:'account-b'},{chainId:'0x1' as const},{privacyAddress:'perc1-b'},{expiresAt:Date.now()-1},{permissionEpoch:2}])('rejects a grant outside its bound context: %o',async update=>{const f=fixture();await f.api.request('https://app.plabs.online',{scopes:['history']});f.change(update);await expect(f.api.read('https://app.plabs.online','history',async()=>[])).rejects.toMatchObject({code:4100});});
 it('isolates websites and revoke blocks future reads',async()=>{const f=fixture();await f.api.request('https://app.plabs.online',{scopes:['notes']});await expect(f.api.read('https://untrusted.example','notes',async()=>[])).rejects.toMatchObject({code:4100});await f.api.revoke('https://app.plabs.online');expect(f.readGrant()).toBeUndefined();});
 it('discards data after locking or switching during a read',async()=>{const f=fixture();await f.api.request('https://app.plabs.online',{scopes:['balances']});await expect(f.api.read('https://app.plabs.online','balances',async()=>{f.change({revision:2});return 'secret';})).rejects.toMatchObject({code:4100});});
 it('does not persist approval when the context changes mid-dialog',async()=>{const f=fixture();f.approve.mockImplementation(async()=>{f.change({revision:2});return true;});await expect(f.api.request('https://app.plabs.online',{scopes:['history']})).rejects.toMatchObject({code:4100});expect(f.readGrant()).toBeUndefined();});
 it('preserves rejection and rejects unsupported or unbounded input',async()=>{const f=fixture();f.approve.mockResolvedValue(false);await expect(f.api.request('https://app.plabs.online',{scopes:['address']})).rejects.toMatchObject({code:4001});expect(()=>readScopes({scopes:['seed']})).toThrow();expect(()=>readScopes({scopes:['address'],privateKey:true})).toThrow();for(const input of [{page:0},{page:1.2},{pageSize:1000},{poolAddress:'bad'},[],{secret:true}])expect(()=>readPagination(input)).toThrow();expect(readPagination({page:2,pageSize:20})).toMatchObject({page:2,pageSize:20});});
});
